# Generated by Django 5.1.4 on 2025-01-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hundred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
